webapp/src/exercise/view/controllers/ConfigurationController.java
package exercise.view.controllers;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import exercise.configuration.Configuration;
import exercise.configuration.ConfigurationRepository;
import exercise.enums.configuration.StaticConfiguration;


@ManagedBean
@ViewScoped
public class ConfigurationController implements Serializable {
	
	@Inject
	private ConfigurationRepository confRepo;
	
	private List<Configuration> allConfigurations = new ArrayList<>();
	private List<StaticConfiguration> allStaticConf = new ArrayList<>();
	
	private Configuration selectedItem = new Configuration();
	private StaticConfiguration itemToOverwrite;
	
	
	@PostConstruct
	public void init() {
	//	if(facesContext.isPostback()) {
	//		return ;
	//	}
		allConfigurations.addAll(confRepo.getAllConfigurations());
		allStaticConf.addAll(Arrays.asList(StaticConfiguration.values()));
	}
	
	public boolean checkIfOverriden(StaticConfiguration itemToCheck) {
		return	(findLocalItemByCode(itemToCheck.getCode()) != null)?true:false;
	}
	
	public void prepereForOverride(StaticConfiguration itemToOverride) {
		this.itemToOverwrite = itemToOverride;
		selectedItem = new Configuration();
		selectedItem.setCode(itemToOverride.getCode());
	}
	
	public void saveSelectedItem() {
		selectedItem.setCode(itemToOverwrite.getCode());
		selectedItem = confRepo.mergeConfiguration(selectedItem);
		Configuration existingItem = findLocalItemByCode(selectedItem.getCode());
		if(existingItem != null) {
			allConfigurations.remove(existingItem);
		}
		allConfigurations.add(selectedItem);
	}
	
	private Configuration findLocalItemByCode(String code) {
		return allConfigurations.stream()
				.filter(conf -> conf.getCode().equalsIgnoreCase(code))
				.findAny()
				.orElse(null);
	}
	
	public void deleteConfiguration(Configuration config) {
			confRepo.removeConfiguration(config);
			allConfigurations.remove(config);
	}
	/*
	 * Getters and Setters
	 */
	public List<Configuration> getAllConfigurations() {
		return allConfigurations;
	}
	
	public List<StaticConfiguration> getAllStaticConfigurations() {
		return allStaticConf;
	}

	public Configuration getSelectedItem() {
		return selectedItem;
	}

	public void setSelectedItem(Configuration selectedItem) {
		this.selectedItem = selectedItem;
	}

}

webapp/WebContent/403.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:p="http://primefaces.org/ui"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:adm="http://github.com/adminfaces"
                template="#{adminConfig.templatePath}">


    <ui:define name="body">
        <div class="error-page">
            <h2 class="headline text-fatal">#{adm['label.403.header']}</h2>

            <div class="error-content" style="font-size: 1.1em">
                <h3><i class="fa fa-lock text-fatal"></i> #{adm['label.403.message']}</h3>

                <p>
                    #{adm['label.go-back']} <p:link style="text-decoration: underline" href="/" value="Home"
                                                    escape="false"/>.
                </p>

            </div>
        </div>
        <adm:sidebar collapsed="true"/>

        <h:form>
            <p:remoteCommand autoRun="true" process="@none" global="false" partialSubmit="true" update="@none" oncomplete="$.AdminLTE.layout.fix()"/>
        </h:form>
    </ui:define>


</ui:composition>

webapp/WebContent/404.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:p="http://primefaces.org/ui"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:adm="http://github.com/adminfaces"
                template="#{adminConfig.templatePath}">


    <ui:define name="body">
        <div class="error-page">
            <h2 class="headline text-yellow">#{adm['label.404.header']}</h2>

            <div class="error-content" style="font-size: 1.1em">
                <h3><i class="fa fa-warning text-yellow"></i> #{adm['label.404.message']}.</h3>

                <p>
                    #{adm['label.go-back']} <p:link style="text-decoration: underline" href="/" value="Home"
                                                     escape="false"/>.
                </p>

            </div>
        </div>
        <adm:sidebar collapsed="true"/>
    </ui:define>


</ui:composition>

webapp/WebContent/500.xhtml
<ui:composition template="#{adminConfig.templatePath}"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:fn="http://java.sun.com/jsp/jstl/functions"
                xmlns:p="http://primefaces.org/ui"
                xmlns:adm="http://github.com/adminfaces"
                xmlns:of="http://omnifaces.org/functions">


    <ui:define name="body">
      <div class="row">
            <div class="ui-g-12"> 
                <div class="error-page">
                    <h2 class="headline text-red">#{adm['label.500.header']}</h2>

                    <div class="error-content" style="font-size: 1.1em">
                        <h3>
                            <i class="fa fa-warning text-red"></i> #{adm['label.500.message']}.
                        </h3>

                        <p>
                            #{adm['label.go-back']} <p:link style="text-decoration: underline" href="/" value="Home"
                                                             escape="false"/>.
                        </p>
                    </div>
                </div>    
         </div>
      </div>          

     <div class="row">
         <div class="ui-g-12"> 
        <div class="box box-solid box-danger">
                <div class="box-header with-border" style="padding-top: 1px">
                    <h3>#{adm['label.500.title']}</h3>
                </div>
                <div class="box-body" style="overflow: auto">
                    <ul>
                        <li><b>Date/time:</b> #{of:formatDate(now, adminConfig.dateFormat)}</li>
                        <li><b>User agent:</b> #{header['user-agent']}</li>
                        <li>
                            <b>User IP:</b> #{empty header['x-forwarded-for'] ? request.remoteAddr : fn:split(header['x-forwarded-for'], ',')[0]}
                        </li>
                        <li><b>Request URI:</b> <a
                                href="#{requestScope['javax.servlet.error.request_uri']}">#{requestScope['javax.servlet.error.request_uri']}</a>
                        </li>
                        <li><b>Ajax request:</b> #{facesContext.partialViewContext.ajaxRequest ? 'Yes' : 'No'}</li>
                        <li><b>Status code:</b> #{requestScope['javax.servlet.error.status_code']}</li>
                        <li><b>Exception type:</b> #{requestScope['javax.servlet.error.exception_type']}</li>
                        <li><b>Message:</b> #{requestScope['javax.servlet.error.message']}</li>
                    </ul>
                </div>
            </div>
            <div class="box box-solid box-warning">
                <div class="box-header with-border" style="padding-top: 1px">
                    <h3>#{adm['label.500.detail']}</h3>
                </div>
                <div class="box-body" style="overflow: auto">
                    <pre>
#{of:printStackTrace(requestScope['javax.servlet.error.exception_stacktrace'])}
					</pre>
                </div>

            </div>
        </div>
      </div>
        <adm:sidebar collapsed="true"/>
    </ui:define>

</ui:composition>

webapp/WebContent/admin-top.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core" xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui" xmlns:adm="http://github.com/adminfaces">

<f:view contentType="text/html">
    <h:head>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/>
        <meta name="apple-mobile-web-app-capable" content="yes"/>
        <meta name="mobile-web-app-capable" content="yes"/>
        <ui:insert name="head"/>
        <ui:insert name="head-end"/>
    </h:head>

    <h:body styleClass="#{skinMB.skin} layout-top-nav hold-transition">

        <style type="text/css">

            body .container {
                width: 100%;
            }

            span.caret {
                margin-left: 3px;
                margin-top: -2px;
            }

            li.dropdown {
                margin-left: -7px
            }

            li.dropdown i {
                float: left;
                padding: 3px 5px 3px 0;
            }

            @media (max-width: 1024px) {
                li.messages-menu, li.notifications-menu, li.tasks-menu {
                    display: none ;
                }

                li.dropdown > a > i {
                    display: none;
                }

                #navbar-search-input {
                    width: 150px;
                }
            }

            @media (max-width: 767px) {
                li.messages-menu, li.notifications-menu, li.tasks-menu {
                    display: inline ;
                }

                li.dropdown > a > i {
                    display: inline;
                }

                #navbar-search-input {
                    width: 100%;
                }

            }

        </style>

        <ui:insert name="body-begin"/>
        <f:loadBundle var="adm" basename="admin"/>
        <p:ajaxStatus rendered="#{adminConfig.renderAjaxStatus}"
                      onstart="showBar();"
                      onsuccess="hideBar();"/>

        <p:dialog modal="true" widgetVar="statusDialog" draggable="false" closable="false"
                  resizable="false" responsive="true" showHeader="false"
                  style="z-index: 9999!important;position: fixed">
            <p:graphicImage library="images" name="ajaxloadingbar.gif"/>
        </p:dialog>


        <div class="wrapper">
            <div id="loader" class="load-bar" style="display: none">
                <div class="bar"></div>
                <div class="bar"></div>
                <div class="bar"></div>
            </div>
            <header class="main-header">
                <nav class="navbar navbar-static-top">
                    <div class="container">
                        <div class="navbar-header">
                            <a href="#{request.contextPath}/" class="navbar-brand">
                                <ui:insert name="logo"/>
                            </a>
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                                <i class="fa fa-bars"></i>
                            </button>
                        </div>

                        <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
                            <ui:insert name="menu"/>

                            <ui:insert name="menu-end"/>
                        </div>
                        <!-- /.navbar-collapse -->
                        <div class="navbar-custom-menu">
                            <ui:insert name="top-menu"/>
                        </div>

                        <div class="center-navbar">
                            <ui:insert name="center-header"/>
                        </div>
                        <!-- /.navbar-custom-menu -->
                    </div>
                    <!-- /.container-fluid -->
                </nav>
            </header>
            <!-- Full Width Column -->
            <div id="content" class="content-wrapper">
                <ui:insert name="content-wrapper"/>
                <div class="container">
                    <!-- Content Header (Page header) -->
                    <section class="content-header">
                        <h1>
                            <ui:insert name="title"/>
                            <small><ui:insert name="description"/></small>
                        </h1>
                        <ui:fragment rendered="#{(adminConfig.renderBreadCrumb) and (empty renderBreadCrumb or renderBreadCrumb eq 'true') }">
                            <ol class="breadcrumb" style="overflow: hidden;">
                                <li style="position: relative;">
                                    <p:link href="/" onclick="clearBreadCrumbs();" style="position: relative;">
                                        <i class="fa fa-home"></i>
                                        Home
                                    </p:link>
                                </li>
                                <ui:repeat value="#{breadCrumbMB.breadCrumbs}" var="b" varStatus="status">
                                    <li class="#{status.last ? 'active':''}">
                                        <h:panelGroup rendered="#{status.last}">
                                            #{b.title}
                                        </h:panelGroup>
                                        <p:link href="#{b.link}" rendered="#{not status.last}" style="color: #3C8DBC;position: relative">
                                            #{b.title}
                                        </p:link>
                                    </li>
                                </ui:repeat>
                            </ol>
                        </ui:fragment>
                        <ui:insert name="content-header"/>
                    </section>

                    <!-- Main content -->
                    <section class="content">
                        <ui:insert name="content-begin"/>
                        <ui:fragment rendered="#{adminConfig.renderMessages}">
                            <div class="row">
                                <div class="col-sm-12">
                                    <p:messages id="messages" closable="true" globalOnly="true" autoUpdate="true"
                                                showDetail="true" severity="error,fatal" escape="false"/>
                                    <!-- we need two messages because info-messages are hidden by javascript  -->
                                    <p:messages id="info-messages" closable="true" autoUpdate="true" showDetail="true"
                                                severity="info,warn" escape="false"/>
                                    <p:tooltip/> <!-- exception messages with type tooltip -->
                                </div>
                            </div>
                        </ui:fragment>

                        <ui:insert name="body"/>
                    </section>
                    <ui:insert name="content-end"/>
                    <!-- /.content -->
                </div>
                <!-- /.container -->
            </div>


            <footer class="main-footer">
                <ui:insert name="footer"/>
            </footer>
            <h:form>
                <p:remoteCommand name="clearBreadCrumbs" actionListener="#{breadCrumbMB.clear}" process="@this"
                                 update="@(.breadcrumb)" partialSubmit="true" global="false"/>
            </h:form>
            <div id="scrollTop" class="ripplelink"
                 style="display:none;position: fixed; bottom: 10px; right: 20px; width: 34px; height: 34px; color: rgb(238, 238, 238); line-height: 34px; text-align: center; background-color: rgb(34, 45, 50); cursor: pointer; border-radius: 50%; z-index: 99999; opacity: 0.7;"
                 onclick="window.scrollTo(0,0)">
                <i class="fa fa-chevron-up" style="position:relative;top: -2px"></i>
            </div>
        </div>
        <!-- ./wrapper -->
        <script type="text/javascript">
            if (isMobile()) {
                window.onscroll = activateScrollToTop
            }
        </script>

        <adm:ripple/>

        <h:outputScript library="primefaces" name="jquery/jquery.js" target="head"/>
        <h:outputScript library="js" name="bootstrap.min.js" target="head"/>
        <h:outputScript library="js" name="admin-lte.min.js" target="head"/>
        <h:outputScript library="js" name="admintemplate.js" target="head"/>

        <ui:fragment rendered="#{adminConfig.autoShowNavbar and (empty autoShowNavbar or autoShowNavbar eq 'true')}">
            <script type="text/javascript">
                $(window).scroll(function () {
                    if (isMobile()) {
                        var minScrollTimeNav = 300;
                        var now = new Date().getTime();
                        if (!scrollTimerNav) {
                            if (now - lastScrollFireTimeNav > (3 * minScrollTimeNav)) {
                                activateAutoShowNavbarOnScrollUp();   // fire immediately on first scroll
                                lastScrollFireTimeNav = now;
                            }
                            scrollTimerNav = setTimeout(function() {
                                scrollTimerNav = null;
                                lastScrollFireTimeNav = new Date().getTime();
                                activateAutoShowNavbarOnScrollUp();
                            }, minScrollTimeNav);
                        }
                    }
                });
            </script>
        </ui:fragment>


    </h:body>

</f:view>
</html>

webapp/WebContent/configuration.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/admin.xhtml"
                xmlns:h="http://java.sun.com/jsf/html">

    <ui:define name="head">
        <title>Excerise</title>
    </ui:define>

    <ui:define name="logo-lg">
        Dashboard
    </ui:define>

    <ui:define name="logo-mini">
        Dash
    </ui:define>

    <ui:define name="menu">
        <ul class="sidebar-menu">
            <li>
                <p:link href="/index.xhtml" onclick="clearBreadCrumbs()">
                    <i class="fa fa-home"></i>
                    <span>Home</span>
                </p:link>
            </li>
	        <li>
	         <p:link href="/configuration.xhtml" onclick="clearBreadCrumbs()">
                    <i class="fa fa-wrench"></i>
                    <span>Configurations</span>
            </p:link>
	        </li>
        </ul>
     </ui:define>

    <ui:define name="top-menu">
        <ui:include src="/includes/top-bar.xhtml"/>
    </ui:define>

      <ui:define name="title">
        <h2 class="align-center">
        </h2>
    </ui:define>

    <ui:define name="description">
	Configuration page
    </ui:define>

    <ui:define name="body">
    
    <h:form id="mainForm">

			<div class="container">

					<h:panelGroup id="jsfWrapperDiv" layout="block" styleClass="row wrapperDivT">
						<div class="col s12">
							<ul class="tabs">
								<li class="tab col s3"><a class="active"
									href="#test1">Static Configuation</a></li>
								<li class="tab col s3"><a href="#test2">Overriden
										Configuration</a></li>
								<li class="tab col s3 disabled"><a href="#test3">Presentation
										Configuration</a></li>
							</ul>
						</div>
						<div id="test1" class="col s12">
							<p:dataTable
								widgetVar="staticConf"
								id="tableCon"
								value="#{configurationController.allStaticConfigurations}"
								var="staticConf">
								<p:column headerText="Configuration Code">
									<p:outputLabel value="#{staticConf.code}"/>
								</p:column>
								<p:column headerText="Initial Value Code">
									<p:outputLabel value="#{staticConf.initialValue}"/>
								</p:column>
								<p:column headerText="Overriden" width="90"
									style="text-align:center;">
									<i
										class="#{(configurationController.checkIfOverriden(staticConf))?'fa fa-fw fa-check':'fa fa-fw fa-times-circle '}"
										style="#{(configurationController.checkIfOverriden(staticConf))?'color:green; font-size:14px;':'color:red; font-size:14px;'}" />
								</p:column>
								<p:column headerText="Actions" width="70">
									<p:commandLink
										type="button"
										update="@widgetVar(dlg2)"
										style="font-size:14px;"
										actionListener="#{configurationController.prepereForOverride(staticConf)}"
										oncomplete="PF('dlg2').show();">
										<i class="fa fa-fw fa-edit" />
									</p:commandLink>

								</p:column>
							</p:dataTable>
							
						</div>
						<div id="test2" class="col s12">
						<p:dataTable
								id="tableConf"
								widgetVar="conf"
								value="#{configurationController.allConfigurations}"
								var="conf">
								<p:column headerText="Configuration Code">
									<p:outputLabel value="#{conf.code}"/>
								</p:column>
								<p:column headerText="Initial Value Code">
									<p:outputLabel value="#{conf.value}"/>
								</p:column>
								<p:column headerText="Actions" width="70">
									<p:commandLink
										type="button"
										update="@widgetVar(staticConf) @widgetVar(conf)"
										style="font-size:14px;"
										actionListener="#{configurationController.deleteConfiguration(conf)}">
										<i class="fa fa-fw fa-trash-alt"></i>
										<p:confirm header="Confirmation" message="The configuration will be permanently deleted. Are you sure?" icon="ui-icon-alert" />
									</p:commandLink>

								</p:column>
							</p:dataTable>
						
						</div>
						<div id="test3" class="col s12">Test 3</div>
					</h:panelGroup>

		
	<p:dialog id="editModal" header="Configuration Edit" widgetVar="dlg2" modal="true" height="300" width="600" closable="true">
			<h:panelGroup id="valueGroup">
				<p:outputLabel  value="Configuration Code"/>
				<p:inputText  value="#{configurationController.selectedItem.code}" readonly="true"/>
				<br/>
				<p:outputLabel value="Configuration Value"></p:outputLabel>
				<p:inputText value="#{configurationController.selectedItem.value}"/>
				</h:panelGroup>
				<h:panelGroup id="actions" layout="block" style="padding-top: 50px; float:right;">
						<p:commandButton value="Close" oncomplete="PF('dlg2').hide();" />
						<p:commandButton value="Save"
							process="@(#valueGroup :input)"
							action="#{configurationController.saveSelectedItem()}"
							oncomplete="PF('dlg2').hide();" update="@widgetVar(staticConf) @widgetVar(conf)"/>
					</h:panelGroup>
	</p:dialog>
	
	<p:confirmDialog global="true" showEffect="fade" hideEffect="fade">
        <p:commandButton value="Yes" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
        <p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
    </p:confirmDialog>

			</div>



		</h:form>

    </ui:define>


    <ui:define name="footer">
          <a target="_blank"
           href="https://github.com/adminfaces/">
            Copyright (C) 2017 - AdminFaces
        </a>

        <div class="pull-right hidden-xs" style="color: gray">
            <i>1.0.0</i>
        </div>
    </ui:define>


</ui:composition>

webapp/WebContent/expired.xhtml
<ui:composition template="#{adminConfig.templatePath}"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:adm="http://github.com/adminfaces"
                xmlns:ui="http://java.sun.com/jsf/facelets">

    <ui:define name="body">
        <div class="error-content">
            <div class="box box-solid box-danger">
                <div class="box-header with-border" style="padding-top: 1px">
                    <h3>#{adm['label.expired.title']}</h3>
                </div>
                <div class="box-body">
                    <p>#{adm['label.expired.message']}.
                        <a href="#{requestScope['javax.servlet.error.request_uri']}">#{adm['label.expired.click-here']}</a>
                    </p>

                </div>
            </div>
        </div>
        <adm:sidebar collapsed="true"/>
        <h:form>
            <p:remoteCommand autoRun="true" process="@none" global="false" partialSubmit="true" update="@none" oncomplete="$.AdminLTE.layout.fix()"/>
        </h:form>
    </ui:define>

</ui:composition>

webapp/WebContent/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/admin.xhtml"
                xmlns:h="http://java.sun.com/jsf/html">

    <ui:define name="head">
        <title>Excerise</title>
    </ui:define>

    <ui:define name="logo-lg">
        Dashboard
    </ui:define>

    <ui:define name="logo-mini">
        Dash
    </ui:define>

    <ui:define name="menu">
        <ul class="sidebar-menu">
            <li>
                <p:link href="/index.xhtml" onclick="clearBreadCrumbs()">
                    <i class="fa fa-home"></i>
                    <span>Home</span>
                </p:link>
            </li>
	        <li>
	         <p:link href="/configuration.xhtml" onclick="clearBreadCrumbs()">
                    <i class="fa fa-wrench"></i>
                    <span>Configurations</span>
            </p:link>
	        </li>
        </ul>
     </ui:define>

    <ui:define name="top-menu">
        <ui:include src="/includes/top-bar.xhtml"/>
    </ui:define>

      <ui:define name="title">
        <h2 class="align-center">
            <br/>
            <small> Welcome to the Project! </small>
        </h2>
    </ui:define>

    <ui:define name="description">

    </ui:define>

    <ui:define name="body">
    
    <h:form>
        <div class="row">
	      <div class="section">
	 		<p:commandButton styleClass="waves-effect waves-light btn" actionListener="#{mainController.handleFile()}" value="Manual File Loading..."/>

	 		<p:commandButton styleClass="waves-effect waves-light btn" actionListener="#{mainController.checkRequestModule()}" value="Call Mock Service.."/>
	      </div>
       </div>
    
   <div class="row">
	<div class="section">
   
  
      <h:panelGroup id="panelTimers" layout="block" >
        <div class="col s6">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
              <span class="card-title center-align">Timers Info</span>
              <p:dataList value="#{mainController.timerInfo}" styleClass="card-content white-text" var="i">
              	<p>#{i}</p>
              </p:dataList>
            </div>
            <div class="card-action">
              <p:commandLink value="Refresh" type="button" actionListener="#{mainController.refreshTimerInfo()}" ajax="true" update="panelTimers"></p:commandLink>
            </div>
          </div>
        </div>
      </h:panelGroup>
            
   
        <h:panelGroup id="failedItems" layout="block" >
        <div class="col s6">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
              <span class="card-title center-align">Failed To Process Transaction </span>
               <p:dataTable id="failedTbl" value="#{mainController.allFailed}"
                var="item"  paginatorTemplate="{PageLinks}">
		        	<p:column headerText="id">
		        		<h:outputLabel value="#{item.id}" />
		        	</p:column>
		        	<p:column headerText="file name">
		        		<h:outputLabel value="#{item.fileName}" style="font-size:12px !important;"/>
		        	</p:column>
		        	<p:column headerText="Received Line">
		        		<h:outputLabel value="#{item.transactionLine}" style="font-size:12px !important;"/>
		        	</p:column>
		        	<p:column headerText="Error Message">
		        		<h:outputLabel value="#{item.errorMessage}" style="font-size:12px !important;"/>
		        	</p:column>
        	</p:dataTable>
            </div>
            <div class="card-action">
              <p:commandLink value="Refresh" type="button" actionListener="#{mainController.rehreshFailed()}" ajax="true" update="failedTbl"></p:commandLink>
            </div>
          </div>
        </div>
      </h:panelGroup>
      
      </div>
      </div>
        
    </h:form>
   
    </ui:define>


    <ui:define name="footer">
          <a target="_blank" style="color: gray">
           Stamatis Mandalakas
        </a>

    </ui:define>


</ui:composition>

webapp/WebContent/optimistic.xhtml
<ui:composition xmlns:adm="http://github.com/adminfaces"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                template="#{adminConfig.templatePath}">

    <ui:define name="body">
        <div class="error-content">
            <div class="box box-solid box-warning">
                <div class="box-header with-border" style="padding-top: 1px">
                    <h3>#{adm['label.optimistic.title']}</h3>
                </div>
                <div class="box-body">
                    <p>#{adm['label.optimistic.message']}
                        <a href="#{requestScope['javax.servlet.error.request_uri']}">#{adm['label.optimistic.click-here']}</a>
                    </p>

                </div>
            </div>
        </div>
        <adm:sidebar collapsed="true"/>

        <h:form>
            <p:remoteCommand autoRun="true" process="@none" global="false" partialSubmit="true" update="@none" oncomplete="$.AdminLTE.layout.fix()"/>
        </h:form>
    </ui:define>

</ui:composition>